# Pin npm packages by running ./bin/importmap

pin "application"
pin "@hotwired/turbo-rails", to: "turbo.min.js"
pin "work-time", to:"work-time.js"
pin "delete", to:"delete.js"
pin "category-work-time-modal", to: "category-work-time-modal.js"
pin "category-income-modal", to: "category-income-modal.js"
pin "category-income-delete", to: "category-income-delete.js"
pin "category-work-modal-delete", to: "category-work-modal-delete.js"
pin "category-expense-modal", to: "category-expense-modal.js"
pin "category-expense-delete", to:"category-expense-delete.js"
pin "form-reload", to:"form-reload.js"
pin "tag-input", to:"tag-input.js"
pin "tag-admin", to:"tag-admin.js"
pin "goal-modal", to:"goal-modal.js"
pin "goal-meter", to:"goal-meter.js"
pin "chartkick", to: "chartkick.js"
pin "Chart.bundle", to: "Chart.bundle.js"
pin "analysis", to: "analysis.js"
pin "work-reports", to: "work-reports.js"
pin "work-report-filter", to: "work-report-filter.js"
pin "album-show", to: "album-show.js"
pin "home-show", to: "home-show.js"
pin "category-variation-alert", to: "category-variation-alert.js"
