# Pin npm packages by running ./bin/importmap

pin "application"
pin "@hotwired/turbo-rails", to: "turbo.min.js"
pin "work_time", to:"work_time.js"
pin "delete", to:"delete.js"
pin "category_work_time_modal", to: "category_work_time_modal.js"
pin "category_income_modal", to: "category_income_modal.js"
pin "income_category_delete", to: "income_category_delete.js"
pin "work_category_modal_delete", to: "work_category_modal_delete.js"
pin "category_expense_modal", to: "category_expense_modal.js"
pin "expense_category_delete", to:"expense_category_delete.js"
pin "form_reload", to:"form_reload.js"
pin "tag_input", to:"tag_input.js"
pin "tag_admin", to:"tag_admin.js"
pin "goal_modal", to:"goal_modal.js"
pin "goal-meter", to:"goal-meter.js"
pin "chartkick", to: "chartkick.js"
pin "Chart.bundle", to: "Chart.bundle.js"
pin "analysis", to: "analysis.js"
pin "work-reports", to: "work-reports.js"
pin "work-report-filter", to: "work-report-filter.js"
pin "album-show", to: "album-show.js"
pin "home-show", to: "home-show.js"
pin "category_variation_alert", to: "category_variation_alert.js"
