// Configure your import map in config/importmap.rb. Read more: https://github.com/rails/importmap-rails
import "@hotwired/turbo-rails"
import "work_time"
import "delete"
import "category_work_time_modal"
import "category_income_modal"
import "income_category_delete"
import "work_category_modal_delete"
import "image_preview"
import "category_expense_modal"
import "expense_category_delete"
import "form_reload"